apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
  namespace: content
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      containers:
        - name: content-service
          image: roin09/content-service:latest
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: content-service-config
            - secretRef:
                name: content-service-secret
